export const MSG_ADD_PRODUCT_TO_CART_SUCCESS = 'ADDED PRODUCT SUCCESSFULLY';
export const MSG_UPDATE_PRODUCT_CART_SUCCESS = 'UPDATED CART SUCCESSFULLY';
export const MSG_DELETE_PRODUCT_IN_CART_SUCCESS = 'DELETED PRODUCT FROM CART SUCCESSFULLY';
export const MSG_CART_EMPTY = 'NOTHING IN CART';
export const MSG_WELCOME = 'WELCOME TO MYSHOP';